name: Test & lint

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir:
          - 1.9-slim    # otp 22
          - 1.8-otp-22
          - 1.8-slim    # otp 21
          - 1.7-slim    # otp 21
    container:
      image: elixir:${{ matrix.elixir }}

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix ua_inspector.download -f

    - name: Run Tests
      run: mix test

  lint:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Format
      run: mix format --check-formatted --dry-run
