name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.9-slim    # otp 22
          - 1.8-otp-22
          - 1.8-slim    # otp 21
          - 1.7-slim    # otp 21
    container:
      image: elixir:${{ matrix.elixir }}
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix ua_inspector.download
    - name: Run Tests
      run: mix test
  format:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-slim
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check Format
      run: mix format --check-formatted --dry-run
